fail_fast: false
default_stages:
  - commit
  - push

repos:
  # run markdown files linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.0
    hooks:
      - id: markdownlint-fix
        args:
          - --config
          - .config/.markdownlint-config.yaml